### ISSUE TITLE
Multus failing in pod creation without network annotation

### ISSUE THREAD

**Issue by rkamudhan** [intel/multus-cni#116]
try with pod spec:

```
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-case-04
spec:
  containers:
  - name: pod-case-04
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
```
