### ISSUE TITLE
Cannot fully control the default route anylonger

### ISSUE THREAD

**Issue by mhristache** [intel/multus-cni#126]
Hi

I have a setup where most of the containers are using only `eth0` and for those I add the default gateway automatically (so that kubernetes services work) by specifying `"isDefaultGateway": true` in the default delegate.

I also have some containers where I need multiple interfaces and I am trying to add the default gateway via another interface but that no longer seem possible with the latest Multus release. 

I am adding a network like this (note the default route):

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: test
spec: 
  config: '{
        "type": "bridge",
        "bridge": "br_test",
        "mtu": 1460,
        "addIf": "true",
        "hairpinMode": true,
        "ipam": {
            "type": "host-local",
            "subnet": "10.8.8.0/24",
            "gateway": "10.8.8.1",
            "routes": [
                {
                    "dst": "0.0.0.0/0"
                }
            ]
        }
    }'
```

And then create the deployment:

```yaml
...
        app: netshoot
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
            {"name": "test"}
        ]'
    spec:
...
```

But the route added via the delegate above does not override the default route added by the default delegate.

Basically, if I add `"isDefaultGateway": true` to the default delegate, the default route will always be via `eth0` and any other default route will be ignored.

This kind of setup was possible with the previous version of Multus as one could specify a different config for the delegate plugin used to create eth0. 

E.g. it was possible before to do something like this:

```yaml
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: bridge-no-default-gw
plugin: bridge
args: '[
    {
        "type": "bridge",
        "mtu": 1460,
        "addIf": "true",
        "hairpinMode": true,
        "ipam": {
            "type": "host-local",
            "subnet": "10.244.0.0/24",
            "gateway": "10.244.0.1",
            "routes": [
                {
                    "dst": "10.96.0.0/12"
                }
            ]
        }
    }
]'
---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: test
plugin: bridge
args: '[
    {
        "type": "bridge",
        "name": "test",
        "bridge": "br_test",
        "mtu": 1500,
        "hairpinMode": true,
        "ipam": {
            "type": "host-local",
            "subnet": "10.8.8.0/24",
            "gateway": "10.8.8.1",
            "routes": [
                {
                    "dst": "0.0.0.0/0"
                }
            ]
        }
    }
]'
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: netshoot
  labels:
    app: netshoot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
      annotations:
        networks: '[
            { "name": "bridge-no-default-gw"},
            { "name": "test"}
        ]'
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot
        tty: true
```

But it seems it's no longer possible to achieve the same behaviour with latest Multus version. 

Or am I missing something?

Let me know if you have any suggestions on how to solve this issue or if you need clarifications.

Thank you

//Max

**Comment by rkamudhan** [comment]
please use the latest Multus v3.0 network object

**Comment by mhristache** [comment]
I am using latest Multus v3.0 network object. As explained in the description I am creating a network-attach-def like this:

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: test
spec: 
  config: '{
        "type": "bridge",
        "bridge": "br_test",
        "mtu": 1460,
        "addIf": "true",
        "hairpinMode": true,
        "ipam": {
            "type": "host-local",
            "subnet": "10.8.8.0/24",
            "gateway": "10.8.8.1",
            "routes": [
                {
                    "dst": "0.0.0.0/0"
                }
            ]
        }
    }'
```
But the default route in the network-attach-def does not override the default route added by the default plugin (flannel).
