### ISSUE TITLE
Concerns about MacVlan with ipam type host-local by CRD

### ISSUE THREAD

**Issue by soyuutaku** [intel/multus-cni#144]
Let say we have a macvlan-conf.yaml:
``` yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan
spec: 
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.2",
        "rangeEnd": "192.168.1.253",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ]
      }
    }'
```

Since we config the ipam type to `host-local`, and this config will effect all nodes in the cluster. Is that possible that pods have same IP allocated in different hosts(All host have interface eth0 connected to same vlan)? That is: POD A on Node A have IP 192.168.1.2, and POD B on Node B have same IP as 192.168.1.2.

**Comment by s1061123** [comment]
@soyuutaku did you check static IPAM plugin above?

**Comment by soyuutaku** [comment]
@s1061123, Sorry for late reply. 

I'm not familiar with static IPAM. So i didn't have a try. Will do some search about static IPAM, and see if it can meet my requirement.

And I'm afraid that I may need create a lot of networks with static IPAM so that every pod have different static IP. If so, it is unacceptable.

**Comment by s1061123** [comment]
@soyuutaku For now, we will plan to configure ip in Pod annotation, as 'section 4.1.2.1.3' of following CRD spec, in a few months.
https://docs.google.com/document/d/1Ny03h6IDVy_e_vmElOqR7UdTPAG_RNydhVE1Kx54kFQ/edit#

BTW, 'host-local' plugin is not multus, so you could file it in "github.com/containernetworking/plugins".

If you're okey, could you please close it?

**Comment by soyuutaku** [comment]
By using CRD spec, we cannot configure different IP range for different Node. 

This limitation should be mentioned in the document.

Will close this issue anyway.

**Comment by s1061123** [comment]
@soyuutaku I suppose your expectation is over the specification of 'host-local' IPAM plugin because 'host-local' is just 'host-local', not 'cluster-local', hence it is not a limitation...

**Comment by hshtel** [comment]
@soyuutaku @s1061123 hello dears;
have you found solution for this issue or workaround so pods attached to macvlan CRD on different hosts get different IP address.
I mean when creating several pods on different hosts with ipam type to host-local the pods are getting the same IP. 

in other words; how we can ensure uniqueness of IP addresses on cluster level not only on host single host?

thanks.

**Comment by dougbtv** [comment]
@hshtel -- would you be willing to give a try at this new IPAM CNI plugin, Whereabotus? https://github.com/dougbtv/whereabouts 

It does what host-local does, but, it does it at a cluster-wide level.

**Comment by soyuutaku** [comment]
@hshtel  I did not manage to use host-local after-all. But I managed to use DHCP, and it works well for me.

To use DHCP, need one DHCP server on the network. and run dhcp on every node.

**Comment by hymgg** [comment]
@soyuutaku could you share how the DHCP server was setup? Thanks.  -Jessica

**Comment by soyuutaku** [comment]
@hymgg what I managed to use dhcp in my cluster, I do as follow:

1. Build DHCP server as this docerfile:
    ```dockerfile
    FROM alpine:3.8

    RUN apk add --no-cache dhcp

    EXPOSE 67/udp 67/tcp

    RUN ["touch", "/var/lib/dhcp/dhcpd.leases"]

    VOLUME ["/etc/dhcp"]

    CMD ["/usr/sbin/dhcpd", "-4", "-f", "-d", "--no-pid", "-cf", "/etc/dhcp/dhcpd.conf"]
    ```

1. Download [`static` plugin](https://github.com/containernetworking/plugins/tree/master/plugins/ipam/static), compile and deploy to nodes in cluster.

1. Start it with this yaml:
    ```yaml
    kind: ConfigMap
    apiVersion: v1
    metadata:
      name: dhcp-server-config
      namespace: default
      labels:
        app: dhcp-server
    data:
      dhcpd.conf: |
        default-lease-time 600;
        max-lease-time 7200;
        authoritative;
        subnet 10.10.0.0 netmask 255.255.0.0 {
            range dynamic-bootp 10.10.0.2 10.10.255.254;
            option broadcast-address 10.10.255.255;
        }
    ---
    apiVersion: "k8s.cni.cncf.io/v1"
    kind: NetworkAttachmentDefinition
    metadata:
      name: macvlan-static
      namespace: default
    spec: 
      config: '{
          "cniVersion": "0.3.0",
          "type": "macvlan",
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "addresses": [
              {
                "address": "10.10.0.1/16"
              }
            ]
          }
        }'
    ---
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: dhcp-server
      labels:
        app: dhcp-server
      namespace: default
    spec:
      replicas: 1
      selector:
        matchLabels:
          tier: dhcp-service
      template:
        metadata:
          namespace: default
          annotations:
            k8s.v1.cni.cncf.io/networks: macvlan-static@dhcp
          labels:
            tier: dhcp-service
            app: dhcp-server
        spec:
          containers:
          - name: dhcp-server
            image: dhcp-server:alpine-3.8
            command: [
              "/usr/sbin/dhcpd", 
              "-4", "-f", "-d", "--no-pid",
              "-cf", "/data/dhcpd.conf",
              "dhcp"
            ]
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: dhcp-server-cfg
              mountPath: /data/dhcpd.conf
              subPath: dhcpd.conf
          volumes:
            - name: dhcp-server-cfg
              configMap:
                name: dhcp-server-config
                items: 
                - key: dhcpd.conf
                  path: dhcpd.conf
    ---
    apiVersion: "k8s.cni.cncf.io/v1"
    kind: NetworkAttachmentDefinition
    metadata:
      name: macvlan
    spec: 
      config: '{
          "cniVersion": "0.3.0",
          "type": "macvlan",
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "dhcp"
          }
        }'

    ```

1. Then run dhcp on each node of cluster:
    ```shell
    cat <EOF > /etc/systemd/system/dhcp.service
    [Unit]
    Description=K8s CNI DHCP Daemon
    After=syslog.target

    [Service]
    WorkingDirectory=/opt/cni/bin
    ExecStartPre=/bin/rm -f /run/cni/dhcp.sock
    ExecStartPre=/sbin/ifconfig eth0 promisc
    ExecStart=/bin/bash -c "/opt/cni/bin/dhcp daemon"
    Restart=always
    StartLimitInterval=0
    RestartSec=10

    [Install]
    WantedBy=multi-user.target
    EOF

    systemctl enable dhcp.service
    systemctl start dhcp

    ```
