### ISSUE TITLE
invalid cni config file

### ISSUE THREAD

**Issue by little-dude** [intel/multus-cni#146]
Hi,

I'm making my first steps with multus, so this is probably a dumb mistake from me. Also, I'm not running multus as a daemonset.

I have the following cni config file:

```json
[root@k8s-master ~]# cat /etc/cni/net.d/70-multus.conflist 
{
    "name": "multus-cni-network",
    "type": "multus",
    "delegates": [
        {
            "type": "flannel",
            "name": "flannel.1",
            "delegate": {
                "isDefaultGateway": true
            }
        }
    ],
    "kubeconfig": "/etc/kube-multus/kube.config.yml"
}
```
My flannel network is defined as with the following yaml

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: flannel-net
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "flannel",
    "delegate": {
        "hairpinMode": true,
        "isDefaultGateway": true
    },
    {
        "type": "portmap",
        "capabilities": {
            "portMappings": true
        }
    }
  }'
```

Here is the description:

```
[root@k8s-master ~]#  kubectl get nodes k8s-master.mvcalab.us.alcatel-lucent.com
NAME                                       STATUS     ROLES     AGE       VERSION
k8s-master.mvcalab.us.alcatel-lucent.com   NotReady   <none>    22d       v1.11.2
[root@k8s-master ~]# kubectl describe net-attach-def
Name:         flannel-net
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"k8s.cni.cncf.io/v1","kind":"NetworkAttachmentDefinition","metadata":{"annotations":{},"name":"flannel-net","namespace":"default"},"spec"...                    
API Version:  k8s.cni.cncf.io/v1
Kind:         NetworkAttachmentDefinition
Metadata:
  Creation Timestamp:  2018-09-04T20:44:31Z
  Generation:          1
  Resource Version:    2994650
  Self Link:           /apis/k8s.cni.cncf.io/v1/namespaces/default/network-attachment-definitions/flannel-net
  UID:                 52d0df4f-b083-11e8-b2cc-ac1f6b034124
Spec:
  Config:  { "cniVersion": "0.3.0", "type": "flannel", "delegate": { "hairpinMode": true, "isDefaultGateway": true }, { "type": "portmap", "capabilities": { "portMappings": true } } }                                                      
Events:    <none>
```

But in the kubelet logs I see:

```
Sep 04 14:27:18 k8s-slave-1.mvcalab.us.alcatel-lucent.com kubelet[2524]: W0904 14:27:18.510329    2524 cni.go:120] Error loading CNI config list file /etc/cni/net.d/70-multus.conflist: error parsing configuration list: no 'plugins' key
Sep 04 14:27:18 k8s-slave-1.mvcalab.us.alcatel-lucent.com kubelet[2524]: W0904 14:27:18.510361    2524 cni.go:172] Unable to update cni config: No valid networks found in /etc/cni/net.d
```
