### ISSUE TITLE
Specify cluster default network with a new CRD object.

### ISSUE THREAD

**Issue by pliurh** [intel/multus-cni#157]
In additional to #131 and #153 , I think it would be better to specify the cluster default network with a CRD object instead of config files. My idea is to create a new CRD object. It may looks like:

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: MultusDefaultNetwork
metadata:
  name: default
spec: 
  networkAttachememntDefinition: default/calico
```

Multus can get the name of default network from this CRD object, then retrieve the CNI config from that networkAttachememntDefinition object. 

There are some advantages I can think of:

1. When administrator want to switch the default network from one to another, he doesn't need to update the file on each node.
2. It ensures consistency of the default network config across the cluster.
3. It can be accessed though kube API.
