### ISSUE TITLE
Reference configuration for multus + OVN/OVS

### ISSUE THREAD

**Issue by kenji-fukasawa** [intel/multus-cni#159]
Hello.  I recently started some testing with multus and OVS.  Here's what I have so far.  I have a kubernetes cluster up and running.  I have tested `ovn-kubernetes`  without multus (by running `ovnkube` with the `--net-controller` flag) and have successfully been able to add pods to the OVS network.  From there, I restarted `ovnkube` without the `--net-controller` flag to disable the OVN kubernetes watcher.  I then setup multus with a `macvlan` network as the default delegate.  That also works fine.  

I then created a `NetworkAttachmentDefinition` for an OVS network.
```
cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ovn-k8s-cni-overlay",
      "master": "br-int",
      "name": "ovn.1",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "11.11.0.0/24",
        "rangeStart": "11.11.0.100",
        "rangeEnd": "11.11.0.220"
      }
    }'
EOF
```

I then spun up a pod referencing that definition.
```
cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: samplepod-ovn
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
        { "name": "ovn-conf" }
    ]'
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
EOF
```

The sample pod never starts and has the following error:
```
Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "9768d65edbd4bf2f2ec9e3d3cb854b2f3de64e323b9d412d5e45ca8d3ac2f67f" network for pod "samplepod-ovn": NetworkPlugin cni failed to set up pod "samplepod-ovn_default" network: CNI request failed with status 400: 'Nil response to CNI request
```

I also see entries for that pod in the `ovnkube` log.
```
time="2018-10-03T09:55:09-06:00" level=info msg="Dispatching pod network request &{ADD default samplepod-ovn 4fd2122c7e7ec26a7bc34b339d1f7b1ed107c055ea7268490264217ded6ae63d /proc/30343/ns/net eth0 0xc4200cbea0 0xc420069920}"
```

I'm guessing I'm not sending the necessary configuration to the OVS CNI plugin based on that error.  At this point I'm at a state of guess and check.  Do you guys happen to have a working reference configuration for multus + OVS that I can take a look at?  Or do you have any suggestions?  Any help would be appreciated.
