### ISSUE TITLE
Network annotations for Deployments not working

### ISSUE THREAD

**Issue by rcsavage** [intel/multus-cni#196]
Hello-

I am running Kubernetes v1.12.2 with the latest Multus version.   When I deploy a single POD using a simple POD deployment descriptor I am able to get my second interface (net1) to appear inside my container.   However, when I add the same network annotation to my "Deployment" descriptor, I am not able to bring up the second interface (net1).  

kubectl edit pod/sample - working
```
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "",
          "ips": [
              "10.35.0.1"
          ],
          "default": true,
          "dns": {}
      },{
          "name": "macvlan-conf",
          "interface": "net1",
          "ips": [
              "192.168.2.232"
          ],
          "mac": "6e:e4:ba:38:5d:2c",
          "dns": {}
      }]
```

Not working 
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
    prometheus.io/scrape: "true"
  creationTimestamp: 2018-11-26T21:45:23Z
  generateName: gwin-5b4d5cff7b-
  labels:
    app: gwin
    pod-template-hash: 5b4d5cff7b
  name: gwin-5b4d5cff7b-lg9rn
  namespace: gateway
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: gwin-5b4d5cff7b
    uid: 940386bb-f1c4-11e8-86b3-525400268c25
  resourceVersion: "3866725"
  selfLink: /api/v1/namespaces/gateway/pods/gwin-5b4d5cff7b-lg9rn
  uid: 9421d7a7-f1c4-11e8-86b3-525400268c25
```

It's as if the annotations for a deployment descriptor are not getting parsed properly, or needs to go in another section.   Can anyone elaborate?

**Comment by rcsavage** [comment]
This is the sample POD which is working

```
---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod-new
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  nodeSelector:
    role: gateway
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
    ports:
    - containerPort: 80
```

This is the Deployment descriptor which is NOT working

```
---
apiVersion: v1
kind: Pod
metadata:
  name: gwin
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  hostNetwork: false
  nodeSelector:
    role: gateway
  volumes:
  - name: dvn-config
    emptyDir: {}
  - name: docker-sock-volume
    hostPath:
      path: {{ .Values.podconfig.volumes.dockersockvolume.hostPath.path }}
      type: {{ .Values.podconfig.volumes.dockersockvolume.hostPath.type }}
  initContainers:
  - name: job-1-init-secure
    image: {{ .Values.global.infra.registryserver }}/{{ .Values.global.dvn.releases.toolbox.image }}
    volumeMounts:
    - name: dvn-config
      mountPath: {{ .Values.dvntoolbox.volumeMounts.dvnconfig }}
    env:
  command: ["/bin/sh", "-c"]
  args:
    - "{{ .Values.gateway.thingtorun }}"
  containers:
  - name: gwin
    image: {{ .Values.global.infra.registryserver }}/{{ .Values.global.dvn.releases.vtc.image }}
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: {{ .Values.gateway.resource.requests.memory }}
        cpu: {{ .Values.gateway.resource.requests.cpu }}
      limits:
        memory: {{ .Values.gateway.resource.limits.memory }}
        cpu: {{ .Values.gateway.resource.limits.cpu }}
    volumeMounts:
    - name: dvn-config
      mountPath: {{ .Values.gateway.volumeMounts.dvnconfig }}
    - name: docker-sock-volume
      mountPath: {{ .Values.gateway.volumeMounts.dockersockvolume }}
    ports:
      - containerPort: {{ .Values.gateway.containerports.Port35000 }}
      - containerPort: {{ .Values.gateway.containerports.Port38000 }}
    command: ["/bin/sh", "-c"]
```
