### ISSUE TITLE
Documentation: Consistent terminology for custom resources

### ISSUE THREAD

**Issue by dougbtv** [intel/multus-cni#225]
**What would you like to be added**: Our documentation has some confusion between the usage of "CRD", "custom resource" and "NetworkAttachmentDefinition", I would like this to be more consistent.

**Why is this needed**: The confusion is that there's the definition itself, the CRD, like:

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: network-attachment-definitions.k8s.cni.cncf.io
spec:
  group: k8s.cni.cncf.io
  version: v1
  scope: Namespaced
  names:
    plural: network-attachment-definitions
    singular: network-attachment-definition
    kind: NetworkAttachmentDefinition
    shortNames:
    - net-attach-def
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            config:
                 type: string
```

and then the objects you create, like:

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.200",
        "rangeEnd": "192.168.1.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.1.1"
      }
    }'
```

It was recommended to me to call the objects "custom resources" or by their proper name, `NetworkAttachmentDefinition`.

This will make for more useful and legible documentation.

Thanks to @s1061123 for noticing the inconsistencies!
