### ISSUE TITLE
Cannot use host-device cni plugin with multus

### ISSUE THREAD

**Issue by hightoxicity** [intel/multus-cni#251]
**What happend**:

Submitting a net attachement config (https://github.com/heptio/cni-plugins/tree/master/plugins/main/host-device) to use host-device:

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ens4-host-device-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "device": "ens4"
    }'
```
After that, I launched the following pod:

```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: default/ens4-host-device-conf
spec:
  containers:
  - image: busybox
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  nodeSelector:
    eegress: "1"
  restartPolicy: Always
```

But my pod is staying in ContainerCreating state.

On describe, this is the error I tracked:

```
  Warning  FailedCreatePodSandBox  5m13s (x4 over 5m19s)  kubelet, k8s-cl1-k8s-node-nf-1  (combined from similar events): Failed create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "8766864534a79ce44d49ac2d372ced6841829060b6b3ca81aba8698f5b1b44d5" network for pod "busybox": NetworkPlugin cni failed to set up pod "busybox_default" network: Multus: Err in loading K8s Delegates k8s args: Multus: Err in getting k8s network from pod: GetK8sNetwork: failed getting the delegate: error in LoadDelegateNetConf: delegate must have the 'type'or 'Plugin' field, failed to clean up sandbox container "8766864534a79ce44d49ac2d372ced6841829060b6b3ca81aba8698f5b1b44d5" network for pod "busybox": NetworkPlugin cni failed to teardown pod "busybox_default" network: Multus: Err in getting k8s network from pod: GetK8sNetwork: failed getting the delegate: error in LoadDelegateNetConf: delegate must have the 'type'or 'Plugin' field]
```

**What you expected to happen**:

My pod in running state with the ens4 interface present on my host binded to the container.
