### ISSUE TITLE
set mac address to an interface

### ISSUE THREAD

**Issue by wei0313** [intel/multus-cni#266]
Hi
I want to have a "fixed" mac-address and my own interface name instead of "net1" for my interface; meaning, which time I redeploy the pod I want the interface to always have the same mac.  Below are my original yaml files.  I have also tried putting my network-definition under /et/cni/multus/net.d/macvlan-conf.conf and change my network-attachment-definition, but this still doesn't work. 
I also tried removing the network-status section and add interfaceRequest: ifname which gives me the interface name I want, but even with macRequest, I am still unable to change the mac-address. I have been googling, and I am unable to find the an example on changing the mac-address. I also looked at code. It seems like delegate.macRequest is always empty string. I traced and found net.macRequest in LoadDelegateNetConf is also empty.  When I enable debug log, I could see my mac in setPodNetworkAnnotation. 
Is it because delegate is not reading from the pod annotation? Where should I config the delegate?  
Does v0.3.1 support macRequest? If so, how should I configure? 
If I want my pod yaml / network-attachment-def yaml to handle the configurations only, do i need to change anything in the multus.conf? If so, would you show an example? 

Here is my network-attachment-definition yaml.
`apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens255f1",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.1.0/24",
        "rangeStart": "192.168.1.200",
        "rangeEnd": "192.168.1.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.1.1"
      },
    }'
`
Here is my pod yaml
`piVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: rhel75-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
    k8s.v1.cni.cncf.io/networks-status: '[{
                          "name": "macvlan-conf",
                          "interface": "agnes-1",
                          "mac": "20:01:02:03:04:05",
                          "ips": [
                              "192.168.1.200"
                          ],
                          "dns": {}
                      }]'
spec:
      containers:
      - name: rhel75base
        image: rhel7.5-base-new:base
        imagePullPolicy: Never
`

Thanks in advance

**Comment by s1061123** [comment]
To configure MAC address, you need:

- to install 'tuning' CNI plugin (you need to build/install from https://github.com/containernetworking/plugins to get the latest because mac address support in tuning is recent), and
- use 'tuning' CNI plugin for network-attachment-def as following (https://github.com/intel/multus-cni/pull/148/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8)

Could you please change your config and check it again?

**Comment by wei0313** [comment]
> * https://github.com/containernetworking/plugins

Will give it a try. 
If later on I need to use ovs instead of macvlan, can I still use tuning on top of ovs? I have been testing with ovs-cni.

**Comment by wei0313** [comment]
Thanks @s1061123  I will give it a try.
If later on I need to use ovs instead of macvlan, can I still use tuning on top of ovs? I have been testing with ovs-cni.

**Comment by SchSeba** [comment]
Hi @wei0313 the question is if the ovs write the mac he assign on a mac filter or something if not yes you can use the tuning.

**Comment by wei0313** [comment]
@SchSeba judging by the ovs-cni code, it reads mac attribute, but since multus is not setting it so it doesn't reflect. I am wondering if using tuning would help in this matter

**Comment by SchSeba** [comment]
Hi @wei0313 if the ovs knows how to read the mac address you can try to configure the pod this way

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-case-01
  annotations:
    k8s.v1.cni.cncf.io/networks: [{"name": "macvlan-conf-1","mac":"20:01:02:03:04:05"}]
spec:
  containers:
  - name: pod-case-01
    image: docker.io/centos/tools:latest
    command:
    - /sbin/init
```

If he can't read the mac but he doesn't configure a mac filter you can use tuning like this

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovs-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "name": "ovs-conf",
      "plugins" : [
        {
          "type": "ovs",
          "bridge": "br1",
          "vlan": 100
        },
        {
          "type": "tuning"
        }
      ]
    }'
```
