### ISSUE TITLE
Multus returns error when calling secondary networks

### ISSUE THREAD

**Issue by sseetharaman6** [intel/multus-cni#281]
**What happend**:
This is similar to https://github.com/intel/sriov-cni/issues/72. When creating containers with multiple networks, Multus returns the following error when trying to configure the secondary networks
```
netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
```
and the pod remains stuck in `ContainerCreating` state. This issue occurs with both `nfvpe/multus:latest` and `nfvpe/multus:snapshot` images.

**What you expected to happen**:
Secondary networks should have been configured correctly. 

**How to reproduce it (as minimally and precisely as possible)**:
Pull the latest version of multus-cni from the master branch and create a pod with secondary network.

**Anything else we need to know?**:
 I have been seeing this issue since last Friday (3/8) , for CRDs that have been working well previously - the latest build is probably broken.  
**Environment**:

- Multus version - latest master branch 
  image path and image ID (from 'docker images') `nfvpe/multus                         snapshot            99a503984739        5 days ago          527MB
`
- Kubernetes version (use `kubectl version`): 1.12.1
- Primary CNI for Kubernetes cluster: Flannel
- OS (e.g. from /etc/os-release): CentOS7.5
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`) 
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov
spec:
  config: '{
  "type": "sriov",
  "name": "sriov-net",
  "ipam": {
    "type": "host-local",
    "subnet": "10.0.2.0/24",
    "rangeStart": "10.0.2.100",
    "rangeEnd": "10.0.2.200",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "10.0.2.1"
  }
}' 
```
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`) 
 ```
apiVersion: v1
kind: Pod
metadata:
  name: testpod01
  labels:
    env: test
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net
spec:
  containers:
  - name: nginx
    image: nginx:1.8
    ports:
    - containerPort: 80
    resources:
      requests:
        intel.com/sriov: '1' 
      limits:
        intel.com/sriov: '1'
 ```
- Other log outputs (if you use multus logging)
