### ISSUE TITLE
oc/kubectl get doesn't work for kind 'NetworkAttachmentDefinition'

### ISSUE THREAD

**Issue by rhrazdil** [intel/multus-cni#295]
Hey guys.
When listing nads with ```oc get NetworkAttachmentDefinition``` the command results with an error: ```error: the server doesn't have a resource type "NetworkAttachmentDefinition"```.

It works as expected when ```net-attach-def``` shortcut is used instead of the KIND ```NetworkAttachmentDefinition```. It should be possible to use the KIND as well

**What happend**:
error: the server doesn't have a resource type "NetworkAttachmentDefinition
**What you expected to happen**:
NAME            AGE
<nad_name>   2h

**How to reproduce it (as minimally and precisely as possible)**:
```# cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovs-net-1
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ovs",
      "bridge": "testbridge"
    }'
EOF
# oc get NetworkAttachmentDefinition
```

**Anything else we need to know?**:

**Environment**:
- Multus version 
multus-cni:v1.4.0
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-03-06T12:06:48Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
- Primary CNI for Kubernetes cluster:
- OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.7 Beta (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:beta:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7 Beta"
- File of '/etc/cni/net.d/'
openshift-network.conf:
```
{
  "cniVersion": "0.2.0",
  "name": "openshift-sdn",
  "type": "openshift-sdn"
}
```
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
```
apiVersion: v1
items:
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    creationTimestamp: 2019-03-29T09:30:40Z
    generation: 1
    name: ovs-net-1
    namespace: default
    resourceVersion: "939292"
    selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/default/network-attachment-definitions/ovs-net-1
    uid: 513374e5-5205-11e9-89a0-fa163eb2fcd4
  spec:
    config: '{ "cniVersion": "0.3.1", "type": "ovs", "bridge": "testbridge" }'
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

**Comment by s1061123** [comment]
Currently we use "network-attachment-definition (network-attachment-definitions)" for custom resource name, so that is why we do not use "NetworkAttachmentDefinition" for its name, as [Spec](https://github.com/K8sNetworkPlumbingWG/multi-net-spec/blob/master/%5Bv1%5D%20Kubernetes%20Network%20Custom%20Resource%20Definition%20De-facto%20Standard.md) defines as following:

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: network-attachment-definitions.k8s.cni.cncf.io
spec:
  group: k8s.cni.cncf.io
  version: v1
  scope: Namespaced
  names:
        plural: network-attachment-definitions
        singular: network-attachment-definition
        kind: NetworkAttachmentDefinition
        shortNames:
        - net-attach-def
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            config:
              type: string
```
