### ISSUE TITLE
how to configure ifname instead default "net1"

### ISSUE THREAD

**Issue by wardenlym** [intel/multus-cni#319]
Hi, 
i am trying to set a custom interface name,

could i get pod interface (with index number) and rename it in somewhere?

**Comment by SchSeba** [comment]
Hi @wardenlym can you try something like this

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{"name":"macvlan-conf","interface","<interface-name>"}]'
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "sleep INF"]
    image: centos
```
