### ISSUE TITLE
Can Multus support not only pod but also deployment in k8s?

### ISSUE THREAD

**Issue by mJace** [intel/multus-cni#348]
I want to use multus in my `deployment` .
But it seems like just add network annotation to the metadata of my deployment is not enough.
And I notice that all the example of multus and sriov-device-plugin are based on the `pod` 

Is Multus support deployment?
Or the only way to use multus is to wrap my Apps. to pods?

**Comment by SchSeba** [comment]
Hi @mJace you can do it without any issue.

just add the annotation to the pod section and not to the deployment one

**Comment by mJace** [comment]
@SchSeba  Thank you.
You mentioned about the `pod` section, did you mean the `template`?   
Since the deployment don't have any pod section (correct me if I'm wrong)  

And adding the annotation in template works.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dm-pod
  template:
    metadata:
      name: dm-pod
      labels:
        app: dm-pod
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
            { "name" : "sriov-lwm2m-dm",
              "namespace": "default" }
        ]'
...
...
```
