### ISSUE TITLE
ping macvlan ip failed

### ISSUE THREAD

**Issue by currycan** [intel/multus-cni#372]
Hello,
    I set up the k8s environment with kubeadm and use calico cni. Then, I create the  multus-cni follwing the: https://github.com/intel/multus-cni/issues/278
 ```yaml
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-1g
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "ens192",
    "ipam": {
      "type": "static",
    }
  }'
---
apiVersion: v1
kind: Pod
metadata:
  name: multus-01-simple
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "macvlan-1g", "ips": "10.177.92.111/24" }]'
spec:
  containers:
  - name: multus-01-simple
    image: docker.io/centos/tools:latest
    command:
      - /sbin/init
```
 the ip is created successed, 
```bash
[root@k8s-master-01 multus-cni]# kubectl exec -it multus-01-simple bash
[root@multus-01-simple /]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: eth0@if212: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1440 qdisc noqueue state UP group default 
    link/ether de:de:f5:97:1a:70 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 100.107.127.78/32 scope global eth0
       valid_lft forever preferred_lft forever
5: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 0a:37:d3:f9:00:df brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.177.92.111/24 brd 10.177.92.255 scope global net1
       valid_lft forever preferred_lft forever
```
but I ping the macvlan IP failed in the VM host
```
[root@k8s-master-01 ~]# ping -c 4 10.177.92.111
PING 10.177.92.111 (10.177.92.111) 56(84) bytes of data.
From 10.177.92.1 icmp_seq=1 Destination Host Unreachable
From 10.177.92.1 icmp_seq=2 Destination Host Unreachable
From 10.177.92.1 icmp_seq=3 Destination Host Unreachable
From 10.177.92.1 icmp_seq=4 Destination Host Unreachable

--- 10.177.92.111 ping statistics ---
4 packets transmitted, 0 received, +4 errors, 100% packet loss, time 3095ms
pipe 4
```
 Could you help me?Thx
