### ISSUE TITLE
Kubernetes 1.16 support

### ISSUE THREAD

**Issue by s1061123** [intel/multus-cni#379]
Kubernetes 1.16 updates DaemonSet as following hence `images/multus-daemonset.yml` and `images/multus-daemonset-crio.yml` needs to be  updated.

DaemonSet updates:
- `apiVersion: apps/v1`
- `spec.selector` is required

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-ds-amd64
  namespace: kube-system
  labels:
    tier: node
    app: multus
spec:
  selector:
    matchLabels:
      name: multus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: multus
  (snip, no changes following)
```

**Comment by dougbtv** [comment]
We'll need two daemonset YAML files, and some documentation to note which version to use.

**Comment by s1061123** [comment]
https://github.com/coreos/flannel/pull/1177

**Comment by jianzzha** [comment]
I updated the multus-daemonset.yml and multus-daemonset-crio.yml on my 1.16 setup, kubectl apply take it without complains, but 00-multus.conf stays unchanged,  no cniVersion added even though it is specified in multus-daemonset.yml. Anyone knows why 00-multus.conf didn't get updated?

**Comment by s1061123** [comment]
So could you please let us know the detail as following:

- multus-daemonset.yml and multus-daemonset-crio.yml
- '/etc/cni/net.d/' contents before invoke daemonset and after

**Comment by jianzzha** [comment]
combined multus-daemonset.yml and multus-daemonset-crio.yml:
https://gist.githubusercontent.com/jianzzha/fe468b9cb84e17187e6bf3923205d85c/raw/ab86d169c3247a4eee86ce2c3511b18212ddf1a0/updated%2520multus-daemonset.yml%2520and%2520multus-daemonset-crio.yml%2520combined

'/etc/cni/net.d/00-multus.conf' contents before invoke daemonset and after (same):
https://gist.githubusercontent.com/jianzzha/fe468b9cb84e17187e6bf3923205d85c/raw/ab86d169c3247a4eee86ce2c3511b18212ddf1a0/00-multus.conf%2520after

As if 00-multus.conf content is locked somehow.

**Comment by s1061123** [comment]
```
      containers:
      - name: kube-multus
        image: nfvpe/multus:v3.3
        command: ["/entrypoint.sh"]
```

`nfvpe/multus:v3.3` is not existed in container registry. So I guess that Pod is not running state.
Could you check your lab?
