### ISSUE TITLE
Define IP in pod's annotation is not working in Multus v3.4

### ISSUE THREAD

**Issue by mJace** [intel/multus-cni#460]
**What happend**:

After I update my multus from v3.2 to v3.4. I cannot define pod's IP in it's annotation.
Pod is still created, but without the second network interface.

**What you expected to happen**:

Assign pod's ip in pod's annotation. 

**How to reproduce it (as minimally and precisely as possible)**:

On k8s v1.14.3, change multus from v3.2 to v3.4

**Environment**:

- Multus version v3.2 -> v3.4
  image path and image ID (from 'docker images')  
 docker.io/nfvpe/multus:v3.2  
 docker.io/nfvpe/multus:v3.4  
- Kubernetes version (use `kubectl version`): v1.14.3
- Primary CNI for Kubernetes cluster: flannel
- OS (e.g. from /etc/os-release): Ubuntu 18.04 LTS Server.
- NetworkAttachment info
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlanstatic
spec:
  config: '{
                "cniVersion": "0.3.1",
                "type": "macvlan",
                "master": "enp129s0f2",
                "mode": "bridge",
                "ipam": {
                        "type": "static"
                }
            }'
```

- Target pod yaml info
```
apiVersion: v1
kind: Pod
metadata:
  name: staticpod3
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "macvlanstatic", "ips":"10.1.1.6/24" }]'
spec:
  containers:
    - name: appcntr1
      image: juamorous/ubuntu-ifconfig-ping
      imagePullPolicy: IfNotPresent
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 300000; done;" ]
```

- Other log outputs (if you use multus logging)
No error message or warning message in multus log or kubelet log.
