### ISSUE TITLE
multus cni is not adding 2nd network card

### ISSUE THREAD

**Issue by psaini79** [intel/multus-cni#540]
I followed the following link and setup the multus daemon set.
https://github.com/intel/multus-cni/blob/master/doc/quickstart.md

Created following networkattachment definition:
```
cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": "ens5",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.0.2.0/24",
        "rangeStart": "10.0.2.2",
        "rangeEnd": "10.0.2.50",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "10.0.2.1"
      }
    }'
EOF
```

Checked the network resource
```
[root@k8master-1 ~]# kubectl get network-attachment-definitions
NAME          AGE
ipvlan-conf   4m45s
```
Created the samplepod
```
at <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  containers:
  - name: samplepod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
EOF
```

Checked the IP
```
[root@k8master-1 ~]# kubectl exec -it samplepod -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if8: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 8950 qdisc noqueue state UP 
    link/ether 8e:78:a5:cd:5c:27 brd ff:ff:ff:ff:ff:ff
    inet 10.244.1.18/24 brd 10.244.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::8c78:a5ff:fecd:5c27/64 scope link 
       valid_lft forever preferred_lft forever
[root@k8master-1 ~]# 

```

Do I need to anything extra to add the second network card?  I verified that all the worker node and master node has ens5 on subnet 10.0.2.0/24.
