### ISSUE TITLE
how to set static ip address for pod in openshift v3.11

### ISSUE THREAD

**Issue by XueCangQiuYe** [intel/multus-cni#546]
Hi, 
I have openshift v3.11 cluster and installed multus v4.2.
I want to set static ip as second ip for pod. The default ip is managered bu openshift-sdn.

I am pretty much new on this, I tried to use macvlan like issues #390 and #278 and successfully set second and static ip for pod.

create network-attachment-definitions:
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec: 
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "static",
            "routes": [
              {
                "dst": "0.0.0.0/0",
                "gw": "10.1.1.1"
              }
            ] 
          }
        }
      ]
    }'
```
create pod 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: samplepod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan-conf",
              "ips": [ "10.1.1.111/24" ]  
            }]'
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: os-harbor-svc.default.svc.cloudos:443/helm/slurm_manager:latest
    ports:
    - containerPort: 80
```

So, pod have second and static ip 10.1.1.111 
But, in my pod's host, 
```shell
[root@node-4654c7 dc]# ping 10.1.1.111
PING 10.1.1.111 (10.1.1.111) 56(84) bytes of data.
^C
--- 10.1.1.111 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 3080ms

[root@node-4654c7 dc]#
```

How can i set it up so that i can ping pod second ip in host ?

Let me briefly explain my needs:
I have a cluster, and it can split to manager type node and computing type node.
I want the manager node run in pod in k8s cluster, and computing node run out of k8s cluster.
So, manager node and computing node need to communicate via tcp, therefore two node need to ping each other successfully, and manager node ip need to be static.

**Comment by s1061123** [comment]
Sorry for the reply late, but let me ask the multus version again because currently multus-cni (this repo) has v3.6 as latest as you see in release page https://github.com/intel/multus-cni/releases , so I would like to know where the version 'v4.2'  comes from.

This feature is implemented at v3.4, hence v3.4, v3.4.1, v3.4.2 and v3.6 has this feature.

For further analysis we need `ip address show` command output in the pod.
Could you please provide the followings?

- what is the actual multus version? (`multus --version` may output the version)
- where the version, 'v4.2', comes from?
- `ip address show` command output in the pod

**Comment by XueCangQiuYe** [comment]
Thanks for your reply. My multus version is v3.2. 
In the past month, I found a `network-attachment-definitions` like :
```yaml
kind: NetworkAttachmentDefinition
apiVersion: "k8s.cni.cncf.io/v1"
metadata:
  name: manager-network
spec: 
  config: '{
    "cniVersion": "0.3.1",
    "name": "manager-network",
    "plugins": [
      {
        "type": "macvlan",
        "master": "eth0",
        "ipam": {
          "type": "static",
          "addresses": [
            {
                "address": "186.31.30.101/22",
                "gateway": "186.31.28.1"
            }
          ],
          "dns": {
            "nameservers" : ["186.31.29.11"]
          }
        }
      },
      {
        "type": "sbr"
      }
    ]
  }'
```
and here is my deployment.yaml annontions
```yaml
annotations:
        k8s.v1.cni.cncf.io/networks: '[
            { "name": "manager-network"
            }]'
```
the ip in the pod  is showing below:
```shell
[root@manager ~]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.242.1.35  netmask 255.255.254.0  broadcast 10.242.1.255
        inet6 fe80::38ee:dff:feb0:f3ff  prefixlen 64  scopeid 0x20<link>
        ether 0a:58:0a:f2:01:23  txqueuelen 0  (Ethernet)
        RX packets 1655795  bytes 122909132 (117.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1059895  bytes 2095587225 (1.9 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 5031153  bytes 2451697435 (2.2 GiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5031153  bytes 2451697435 (2.2 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

net1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 186.31.30.101  netmask 255.255.252.0  broadcast 186.31.31.255
        inet6 fe80::fc61:f0ff:fe1c:cd0e  prefixlen 64  scopeid 0x20<link>
        ether fe:61:f0:1c:cd:0e  txqueuelen 0  (Ethernet)
        RX packets 7067911  bytes 725607243 (691.9 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6128707  bytes 1308763010 (1.2 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
It works well, but still got one issue. let briefly show my openshift cluster setting:
I have 3 openshift nodes 186.31.29.11 186.31.29.12 186.31.29.13
The gateway for openshift is 186.31.28.1, same for second ip in the pod

**Here is the issue:**
I create a pod with ip 186.31.30.101, the pod running on the node3(ip 186.31.29.13)
**In pod , I can't ping node3 186.31.29.13 via net1** 
```shell
[root@manager ~]# ping -I net1 186.31.29.13
PING 186.31.29.13 (186.31.29.13) from 186.31.30.101 net1: 56(84) bytes of data.
^C
--- 186.31.29.13 ping statistics ---
6 packets transmitted, 0 received, 100% packet loss, time 5135ms
```

**In node3, I can't ping pod 186.31.30.101** 
```shell
[root@node-3 ~]# ping 186.31.30.101
PING 186.31.30.101 (186.31.30.101) 56(84) bytes of data.
^C
--- 186.31.30.101 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2047ms
```

node1, node2 and pod can ping eachother.

So, Why is this?
How to set yaml so that pod can successfully ping node1-3?
