### ISSUE TITLE
attach additional network interface connected to the flannel network to a pod with hostNetwork: true 

### ISSUE THREAD

**Issue by dorsany** [intel/multus-cni#587]
There is any way to  attach additional network interface which is connected to the flannel network to a pod with `hostNetwork: true` ?

my configuration:
```
git clone https://github.com/intel/multus-cni.git && cd multus-cni
cat ./images/multus-daemonset.yml | kubectl apply -f -
```

NetworkAttachmentDefinition.yaml
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: flannel
spec:
  config: |
    {
        "cniVersion": "0.3.1",
        "plugins": [
          {
            "type": "flannel",
            "delegate": {
              "hairpinMode": true,
              "isDefaultGateway": true
            }
          },
          {
            "type": "portmap",
            "capabilities": {"portMappings": true},
            "snat": true
          }
        ]
    }

```

pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  annotations:
    k8s.v1.cni.cncf.io/networks: flannel
spec:
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
  - name: ubuntu
    image: ubuntu
    command: ['sleep', '3600']
```
So when there is no `hostNetwork: true` enabled, I can see an additional nic connected to the flannel network, but when I was enabled the `hostNetwork: true` no additional nic has been created.

is that by design? something that I'm doing wrong?
