### ISSUE TITLE
macvlan addresses not connectable from other subnets?

### ISSUE THREAD

**Issue by RandomGHUser** [intel/multus-cni#598]
# The Problem
When I assign a macvlan address to a pod, I am able to access it from the subnet in which it is located, but I cannot access it from devices in a different subnet.  
## Example

Below is a basic deployment and network config, which will deploy nginx and set it for a static address of 192.168.0.47:
```yaml
---
### STATIC MACVLAN ADDRESS ###
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: static-192-168-0-47
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.0.0/24",
        "rangeStart": "192.168.0.47",
        "rangeEnd": "192.168.0.47",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.0.1"
      }
    }'
---
### DEPLOYMENT ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: static-192-168-0-47
      namespace: default
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
### SERVICE ###
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
  name: nginx
  namespace: default
spec:
  ports:
    - name: nginx-port-1
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    name: nginx
  sessionAffinity: None
---
```
With the above example, I am able to access this pod  (192.168.0.47:80) from any device in the 192.168.0.0 network.  **The problem is that I cannot access it from my other (for example, 192.168.10.0) networks.**

It is not a router configuration issue, nor an "allow multiple macs/spoofing issue", as all of my other servers can be contacted, and **the "equivalent" docker-compose configuration works on the exact same server.**

## Docker-compose example that works properly

With the "equivalent" docker-compose example below, I *am able* to access 192.168.0.47:80 from any of my subnets.
```yaml
version: "2.3"
networks:
  network:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    restart: always
    networks:
      network:
        ipv4_address: 192.168.0.47
```

## What has been attempted
I've tried setting my network as a static IP, and also setting the dst and and gw route keys (192.168.0.0/24, 192.168.0.1, respectively) based on this document: https://docs.openshift.com/container-platform/4.5/networking/multiple_networks/configuring-macvlan.html

## Presumption

I am presuming there is a simple multus or base-level k8s network configuration option that I've overlooked that will open it up to other subnets.  Any help is appreciated.

**Comment by s1061123** [comment]
This is not multus problem, network problem, I guess.

I suspect your pod's network namespace configures cluster network as default route, hence, nginx try to send http reply to request sender through cluster network. Could you check your pod network route and try to change default route (or specific route) to net1 interface, not eth0? (note: you may need to add `ip` command because nginx may not have it)

**Comment by RandomGHUser** [comment]
Could you please elaborate on how to accomplish this?   I am using a fresh install of bare-metal k8s with flannel, with this simplified yaml:
```yaml
---
### STATIC MACVLAN ADDRESS ###
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: static-net1
  namespace: default
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "eth0",
    "mode": "bridge",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "10.45.7.98/24",
          "gateway": "10.45.7.1"
        }
      ]
    }
  }'
---
### DEPLOYMENT ###
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nettool
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nettool
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: static-net1
      namespace: default
      labels:
        name: nettool
    spec:
      containers:
        - name: nettool
          image: praqma/network-multitool
          ports:
            - containerPort: 80
```

IP route in the pod:
```sh
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         10.244.0.1      0.0.0.0         UG    0      0        0 eth0
10.45.7.0       *               255.255.255.0   U     0      0        0 net1
10.244.0.0      *               255.255.255.0   U     0      0        0 eth0
10.244.0.0      10.244.0.1      255.255.0.0     UG    0      0        0 eth0
```
I can access another subnet directly from each interface in the pod:
```sh
bash-5.0# traceroute -i net1 10.45.6.18
traceroute to 10.45.6.18 (10.45.6.18), 30 hops max, 46 byte packets
 1  10.45.7.1 (10.45.7.1)  3.007 ms  1.254 ms  1.325 ms
 2  10.45.6.18 (10.45.6.18)  0.501 ms  0.644 ms  0.487 ms
bash-5.0# traceroute -i eth0 10.45.6.18
traceroute to 10.45.6.18 (10.45.6.18), 30 hops max, 46 byte packets
 1  10.244.0.1 (10.244.0.1)  0.007 ms  0.004 ms  0.003 ms
 2  10.45.7.1 (10.45.7.1)  1.054 ms  1.075 ms  0.879 ms
 3  10.45.6.18 (10.45.6.18)  0.555 ms  0.182 ms  0.547 ms
```
But again, cannot access the pod macvlan address from the other subnet.

It seems the incoming traffic from other subnets is not being routed properly, and if there is extra configuration I am required to do with my CNI configuration (multus or flannel), could you point me in the direction to resolve this?    It is a pretty simple problem to test (install k8s, install flannel and multus, apply the above yaml, then curl the macvlan address from another subnet).
