### ISSUE TITLE
Attach multiple interfaces for same network

### ISSUE THREAD

**Issue by kiemlicz** [intel/multus-cni#618]
I have a fairly simple use case: how to create secondary interface in the POD and attach it to the same network as the default interface?

My deployment is EKS. I'm using Calico. AWS CNI completely removed

Relevant multus config:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-config
  namespace: kube-system
  labels:
    tier: node
    app: multus
data:
  # NOTE: If you'd prefer to manually apply a configuration file, you may create one here.
  # In the case you'd like to customize the Multus installation, you should change the arguments to the Multus pod
  # change the "args" line below from
  # - "--multus-conf-file=auto"
  # to:
  # "--multus-conf-file=/tmp/multus-conf/70-multus.conf"
  # Additionally -- you should ensure that the name "70-multus.conf" is the alphabetically first name in the
  # /etc/cni/net.d/ directory on each node, otherwise, it will not be used by the Kubelet.
  cni-conf.json: |
    {
      "name": "multus-cni-network",
      "type": "multus",
      "cniVersion": "0.3.1",
      "LogLevel": "debug",
      "LogFile": "/var/log/multus.log",
      "confDir": "/etc/cni/net.d/",
      "readinessindicatorfile": "/etc/cni/net.d/10-calico.conflist",
      "capabilities": {
        "portMappings": true
      },
      "delegates": [
        {
          "cniVersion": "0.3.1",
          "name": "default-cni-network",
          "plugins": [
              {
                           "name": "k8s-pod-network",
                           "cniVersion": "0.3.1",
                           "type": "calico",
                           "log_level": "info",
                           "datastore_type": "kubernetes",
                           "nodename": "__KUBERNETES_NODE_NAME__",
                           "mtu": 1440,
                           "ipam": {
                             "type": "calico-ipam"
                           },
                           "policy": {
                             "type": "k8s"
                           },
                           "kubernetes": {
                             "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
                           }
              },
              {
                "type": "portmap",
                "snat": true,
                "capabilities": {
                  "portMappings": true
                }
              }
          ]
        }
      ],
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
    }
```
DaemonSet relevant part:
```
      containers:
      - name: kube-multus
        image: docker.io/nfvpe/multus:stable
        env:
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        command:
          - /bin/bash
          - -cex
          - |
            #!/bin/bash
            sed "s|__KUBERNETES_NODE_NAME__|${KUBERNETES_NODE_NAME}|g" /tmp/multus-conf/00-multus.conf.template > /tmp/00-multus.conf
            /entrypoint.sh \
              --multus-conf-file=/tmp/00-multus.conf
```

I've created testing purpose:  
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: calico-conf
  namespace: kube-system
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "calico",
    "log_level": "info",
    "datastore_type": "kubernetes",
    "nodename": "ip-10-11-2-68.eu-west-1.compute.internal",
    "mtu": 1440,
    "ipam": {
      "type": "calico-ipam"
    },
    "policy": {
      "type": "k8s"
    },
    "kubernetes": {
      "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
    }
  }'
```
**First question**: I understand that no matter the fact that the default network `calico-config` is present somewhere in `kube-system` ConfigMap I still have to create NetworkAttachmentDefinition?

And the POD, relevant fragment
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: kube-system/calico-conf
  labels:
    role: debug
    app: application
  name: app
```

The POD actually starts (logs show that actually two IPs were assigned) and immediately completes (!)
Digging in logs showed something about eth0 going down (during second IP request)

**Second question** what should I change in order to start my pod with two IPs (routable across the cluster!)?

**Third question** does anyone has working example of multi interface POD setup? Not `host-local`

**Fourth question** Why all examples use `host-local`?! How to make it route across the cluster (across k8s nodes)? Without routing this is completely useless feature
